# Generated by Django 6.1 on 2026-09-02 03:27

import apps.profiles.models
import apps.profiles.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='Name displayed on your matrimonial profile.', max_length=100, verbose_name='display name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='gender')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, help_text='Height in centimeters (e.g. 175).', null=True, verbose_name='height (cm)')),
                ('marital_status', models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('annulled', 'Annulled'), ('awaiting_divorce', 'Awaiting Divorce')], default='never_married', max_length=20, verbose_name='marital status')),
                ('profile_created_for', models.CharField(choices=[('self', 'Self'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend'), ('relative', 'Relative')], default='self', max_length=20, verbose_name='profile created for')),
                ('religion', models.CharField(default='Not Specified', max_length=50, verbose_name='religion')),
                ('caste', models.CharField(blank=True, max_length=50, verbose_name='caste / community')),
                ('sub_caste', models.CharField(blank=True, max_length=50, verbose_name='sub-caste')),
                ('mother_tongue', models.CharField(default='English', max_length=50, verbose_name='mother tongue')),
                ('country', models.CharField(default='United States', max_length=100, verbose_name='country')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state / province')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('citizenship', models.CharField(blank=True, max_length=100, verbose_name='citizenship')),
                ('about_me', models.TextField(blank=True, help_text='Write a short introduction about yourself, your background, and what you value.', max_length=2000, verbose_name='about me')),
                ('visibility', models.CharField(choices=[('public', 'Public (Visible to everyone)'), ('registered_only', 'Registered Members Only'), ('connections_only', 'Accepted Connections Only')], default='registered_only', max_length=20, verbose_name='profile visibility')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by platform administrators.', verbose_name='is verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'matrimonial profile',
                'verbose_name_plural': 'matrimonial profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfessionDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occupation', models.CharField(max_length=100, verbose_name='occupation / job title')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='industry / sector')),
                ('employer', models.CharField(blank=True, max_length=150, verbose_name='company / employer')),
                ('annual_income', models.CharField(blank=True, help_text='e.g. "$75,000 - $100,000" or "INR 15-20 Lakhs"', max_length=60, verbose_name='annual income range')),
                ('working_city', models.CharField(blank=True, max_length=100, verbose_name='working city')),
                ('working_country', models.CharField(blank=True, max_length=100, verbose_name='working country')),
                ('income_visible', models.BooleanField(default=True, help_text='If unchecked, income will only be visible to accepted connections.', verbose_name='make income visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profession', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_age', models.PositiveSmallIntegerField(default=18, verbose_name='minimum age')),
                ('max_age', models.PositiveSmallIntegerField(default=45, verbose_name='maximum age')),
                ('min_height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='minimum height (cm)')),
                ('max_height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum height (cm)')),
                ('preferred_marital_status', models.CharField(blank=True, help_text='Comma-separated choices or leave empty for any.', max_length=100, verbose_name='preferred marital status')),
                ('preferred_religion', models.CharField(blank=True, max_length=100, verbose_name='preferred religion')),
                ('preferred_mother_tongue', models.CharField(blank=True, max_length=100, verbose_name='preferred mother tongue')),
                ('preferred_education', models.CharField(blank=True, max_length=100, verbose_name='preferred education')),
                ('preferred_occupation', models.CharField(blank=True, max_length=100, verbose_name='preferred occupation')),
                ('preferred_country', models.CharField(blank=True, max_length=100, verbose_name='preferred country')),
                ('preferred_diet', models.CharField(blank=True, max_length=100, verbose_name='preferred diet')),
                ('notes', models.TextField(blank=True, help_text='Specific qualities or values you cherish in a prospective partner.', max_length=1000, verbose_name='partner expectations / notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diet', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('eggetarian', 'Eggetarian'), ('vegan', 'Vegan'), ('halal', 'Halal Only'), ('jain', 'Jain Diet'), ('other', 'Other')], default='non_vegetarian', max_length=20, verbose_name='dietary preferences')),
                ('smoking', models.CharField(choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('socially', 'Socially'), ('regularly', 'Regularly')], default='never', max_length=20, verbose_name='smoking habit')),
                ('drinking', models.CharField(choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('socially', 'Socially'), ('regularly', 'Regularly')], default='never', max_length=20, verbose_name='drinking habit')),
                ('hobbies', models.CharField(blank=True, help_text='e.g. Photography, Hiking, Reading, Cooking', max_length=255, verbose_name='hobbies & interests')),
                ('spoken_languages', models.CharField(blank=True, help_text='e.g. English, Bengali, Hindi, Spanish', max_length=255, verbose_name='spoken languages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_type', models.CharField(choices=[('nuclear', 'Nuclear Family'), ('joint', 'Joint Family'), ('other', 'Other')], default='nuclear', max_length=20, verbose_name='family type')),
                ('family_values', models.CharField(choices=[('traditional', 'Traditional'), ('moderate', 'Moderate'), ('liberal', 'Liberal')], default='moderate', max_length=20, verbose_name='family values')),
                ('family_status', models.CharField(blank=True, choices=[('middle_class', 'Middle Class'), ('upper_middle_class', 'Upper Middle Class'), ('rich', 'High / Affluent Class'), ('other', 'Other')], max_length=25, verbose_name='family financial status')),
                ('father_occupation', models.CharField(blank=True, max_length=100, verbose_name="father's occupation")),
                ('mother_occupation', models.CharField(blank=True, max_length=100, verbose_name="mother's occupation")),
                ('brothers_count', models.PositiveSmallIntegerField(default=0, verbose_name='number of brothers')),
                ('sisters_count', models.PositiveSmallIntegerField(default=0, verbose_name='number of sisters')),
                ('living_with_parents', models.BooleanField(default=False, verbose_name='living with parents')),
                ('family_location', models.CharField(blank=True, max_length=150, verbose_name='family native / base location')),
                ('about_family', models.TextField(blank=True, max_length=1000, verbose_name='about family')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('highest_education', models.CharField(choices=[('doctorate', 'Doctorate / Ph.D.'), ('masters', "Master's Degree"), ('bachelors', "Bachelor's Degree"), ('diploma', 'Diploma / Associate Degree'), ('high_school', 'High School'), ('trade_school', 'Vocational / Trade School'), ('other', 'Other')], default='bachelors', max_length=20, verbose_name='highest education')),
                ('ug_degree', models.CharField(blank=True, max_length=100, verbose_name='undergraduate degree')),
                ('pg_degree', models.CharField(blank=True, max_length=100, verbose_name='postgraduate degree')),
                ('institution', models.CharField(blank=True, max_length=150, verbose_name='college / university')),
                ('field_of_study', models.CharField(blank=True, max_length=100, verbose_name='field of study / major')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.profiles.models.profile_photo_upload_path, validators=[apps.profiles.validators.validate_profile_photo])),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='photo caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary photo')),
                ('is_approved', models.BooleanField(default=True, verbose_name='approved by moderation')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('visibility', models.CharField(choices=[('public', 'Visible to All Members'), ('connections_only', 'Visible to Accepted Connections Only')], default='public', max_length=20, verbose_name='photo privacy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'profile photo',
                'verbose_name_plural': 'profile photos',
                'ordering': ['-is_primary', 'order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender', 'marital_status'], name='profiles_pr_gender_570c31_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['religion', 'mother_tongue'], name='profiles_pr_religio_fd2ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country', 'city'], name='profiles_pr_country_d83f94_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_verified', 'visibility'], name='profiles_pr_is_veri_909057_idx'),
        ),
    ]
