# Generated by Django 6.1 on 2026-09-02 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, help_text='Optional reason for blocking.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'block',
                'verbose_name_plural': 'blocks',
                'indexes': [models.Index(fields=['user'], name='connections_user_id_d6a36d_idx'), models.Index(fields=['blocked_user'], name='connections_blocked_9d66e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'blocked_user'), name='unique_user_block'), models.CheckConstraint(condition=models.Q(('user', models.F('blocked_user')), _negated=True), name='block_user_blocked_different')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='profiles.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favorite',
                'verbose_name_plural': 'favorites',
                'indexes': [models.Index(fields=['user', '-created_at'], name='connections_user_id_bd33ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'profile'), name='unique_user_favorite_profile')],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message to accompany the interest.', max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'interest',
                'verbose_name_plural': 'interests',
                'indexes': [models.Index(fields=['receiver', 'status'], name='connections_receive_081ddf_idx'), models.Index(fields=['sender', 'status'], name='connections_sender__07378c_idx'), models.Index(fields=['status', '-sent_at'], name='connections_status_bfada7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'receiver'), name='unique_pending_interest'), models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='interest_sender_receiver_different')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('fake_profile', 'Fake Profile'), ('inappropriate_content', 'Inappropriate Content'), ('harassment', 'Harassment'), ('scam', 'Scam / Fraud'), ('offensive_language', 'Offensive Language'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the issue.', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on the resolution.')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'indexes': [models.Index(fields=['reported_user', 'status'], name='connections_reporte_9fd7eb_idx'), models.Index(fields=['status', '-created_at'], name='connections_status_e55e30_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reporter', models.F('reported_user')), _negated=True), name='report_reporter_reported_different')],
            },
        ),
    ]
